### environement
@baseUrl = http://localhost:8080/api/v1/products

### Create a new product
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Product C",
  "productionTimeHours": 48,
  "costPerUnit": 119.99,
  "stock": 200
}

### Get all products
GET {{baseUrl}}?page=1&size=10

### Get product by ID
GET {{baseUrl}}/3

### Update product by ID
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "name": "Updated Product A",
  "productionTimeHours": 72,
  "costPerUnit": 214.99,
  "stock": 1500
}

### Delete product by ID
DELETE {{baseUrl}}/10

### Get product by name
GET {{baseUrl}}/search?name=Product%20A
