### environment
@baseUrl = http://localhost:8080/api/v1/roles

###
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "CHEF_PRODUCTION"
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/2

###
PUT {{baseUrl}}/20
Content-Type: application/json

{
    "name": "superadmin"
}

###
DELETE {{baseUrl}}/20