### environment
@baseUrl = http://localhost:8080/api/v1/users

POST {{baseUrl}}
Content-Type: application/json

{
  "firstName": "test2",
  "lastName": "test2",
  "email": "test2@gmail.com",
  "password": "12345678",
  "isActive": true,
  "isDeleted": false,
  "roleId": 1
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/1

###
PUT {{baseUrl}}/2
Content-Type: application/json

{
  "firstName": "mouad",
  "lastName": "hallaffou",
  "email": "mouadhlf@gmail.ma",
  "password": "00000000",
  "isActive": true,
  "isDeleted": false,
  "roleId": 1
}

###
PUT {{baseUrl}}/activate/3

###
PUT {{baseUrl}}/deactivate/5

###
PUT {{baseUrl}}/softDelete/2