### environement
@baseUrl = http://localhost:8080/api/v1/clients

### Get all clients
GET {{baseUrl}}?page=0&size=10&sortBy=name&sortDir=asc

### Get client by ID
GET {{baseUrl}}/1

### Create a new client
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "maroc telecom",
  "email": "tele@gmail.com",
  "phoneNumber": "0678901222"
}

### Update a client
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "name": "orange",
  "email": "org@gmail.com",
  "phoneNumber": "0678901234"
}

### Delete a client
DELETE {{baseUrl}}/1