### environnement
@baseUrl = http://localhost:8080/api/v1/matieres-premieres

###
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Chocolat",
  "stockMinimum": 150,
  "stockQuantity": 500,
  "unit": "kg",
  "fournisseurIds": [
    2
  ]
}


###
GET {{baseUrl}}?page=0&size=10

###
GET {{baseUrl}}/3

###
PUT {{baseUrl}}/3
Content-Type: application/json

{
  "name": "Acier Inoxydable",
  "stockMinimum": 150.00,
  "stockQuantity": 450,
  "unit": "kg",
    "fournisseurIds": [
        2
    ]
}

###
DELETE {{baseUrl}}/5

### filter par stock minimum
GET {{baseUrl}}/filtrer-par-stock-critique?stockCritique=150&page=0&size=5

